import CoreMotion
//
//  ManageGesturesView.swift
//  GApp2
//
//  Created by Robert Talianu
//
import SwiftUI

struct About: View {
    @Environment(\.dismiss) var dismiss
    
    
    // constructor
    init() {
      
    }
        
    // The app panel
    var body: some View {
        return VStack {
            Spacer().frame(height: 30)
           
            Text("This app handles the execution of commands mapped to gestures generated by an iPhone device")
                .font(.title3)
            Button("Go Back Button") {
                Globals.log("Go Back Button Clicked...")
                dismiss()
                
            }.buttonStyle(.borderedProminent)
            Spacer()
              
        }
    }
}

